# Generated by Django 4.0.5 on 2022-06-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Follows',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='followig',
            new_name='followed_users',
        ),
    ]
