# Generated by Django 4.0.5 on 2022-06-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='img',
            new_name='image',
        ),
    ]
