# Generated by Django 4.0.5 on 2022-07-28 15:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_img_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.rename_image),
        ),
    ]
