# Generated by Django 4.0.5 on 2022-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_follows_follow_remove_route_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
