# Generated by Django 4.0.5 on 2022-07-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
