# Generated by Django 4.0.5 on 2022-07-31 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_route_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_route', to=settings.AUTH_USER_MODEL),
        ),
    ]
