# Generated by Django 4.0.5 on 2022-08-06 13:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_route_author_alter_wall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='0', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='0', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=api.models.rename_image, width_field='image_width'),
        ),
    ]
