# Generated by Django 4.0.5 on 2022-08-07 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wall_image_height_wall_image_width_alter_wall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='likes',
            field=models.ManyToManyField(related_name='liked_route', to=settings.AUTH_USER_MODEL),
        ),
    ]
