# Generated by Django 4.0.5 on 2022-09-12 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_route_location_alter_route_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_route', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='route',
            name='likes',
        ),
        migrations.AddField(
            model_name='route',
            name='likes',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
    ]
