# Generated by Django 4.0.5 on 2022-09-12 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_route_liked_by_remove_route_likes_route_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wall',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_walls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='location',
            name='likes',
        ),
        migrations.AddField(
            model_name='location',
            name='likes',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wall',
            name='likes',
        ),
        migrations.AddField(
            model_name='wall',
            name='likes',
            field=models.PositiveIntegerField(default='0', editable=False),
        ),
    ]
