# Generated by Django 4.0.5 on 2022-09-14 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_location_created_by_wall_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wall',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_walls', to=settings.AUTH_USER_MODEL),
        ),
    ]
