# Generated by Django 4.0.5 on 2022-09-14 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_location_liked_by_alter_wall_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
