# Generated by Django 4.0.5 on 2022-09-15 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_follow_followed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='created_by',
        ),
        migrations.AddField(
            model_name='location',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wall',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
